# Generated by Django 2.2.3 on 2019-07-27 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190724_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaker',
            name='name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='name',
        ),
        migrations.AddField(
            model_name='speaker',
            name='first_name',
            field=models.CharField(default='', max_length=30, verbose_name='first name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speaker',
            name='last_name',
            field=models.CharField(default='', max_length=30, verbose_name='last name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='first_name',
            field=models.CharField(default='', max_length=30, verbose_name='first name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='last_name',
            field=models.CharField(default='', max_length=30, verbose_name='last name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='speaker',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Choose Your Event:', null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
    ]
