# Generated by Django 2.2.3 on 2019-07-28 11:14

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190727_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='picture',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='pics/speakers/'),
        ),
    ]
