# Generated by Django 2.2.3 on 2019-07-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_staff_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='bio',
            field=models.TextField(default='', help_text='description about person e.g. role in team achievements'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='github_account',
            field=models.CharField(blank=True, help_text='github.com/[User_Account]', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='linkedin_account',
            field=models.CharField(blank=True, help_text='linkedin.com/in/[User_Account]', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='picture',
            field=models.ImageField(default='', help_text="team's picture", upload_to='pics/team/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('arrangement', 'Arrangement'), ('designer', 'Designer'), ('programmer', 'Programmer'), ('talk team', 'Talk Team'), ('others', 'Others')], default='others', help_text="team's way of association in team", max_length=30),
        ),
        migrations.AddField(
            model_name='staff',
            name='slug',
            field=models.SlugField(default='', help_text='link to team bio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(help_text="staff's full name", max_length=30, verbose_name='full name'),
        ),
    ]
