# Generated by Django 2.2.3 on 2019-07-18 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20190717_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='slug',
        ),
    ]
