# Generated by Django 2.2.3 on 2019-07-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20190718_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='bio',
            field=models.TextField(blank=True, help_text='description about person e.g. role in team achievements', null=True),
        ),
    ]
