# Generated by Django 2.2.3 on 2019-07-19 10:28

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20190718_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('picture', models.ImageField(default='default.jpg', upload_to='pics/speakers/')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('professions', models.TextField(max_length=500)),
                ('account_status', models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive')], default='deactive', max_length=20)),
                ('event', models.ForeignKey(help_text='Choose Your Event:', on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
    ]
