# Generated by Django 2.2.3 on 2019-07-20 22:45

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_speaker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_organization', models.CharField(help_text='sponsor company', max_length=50)),
                ('name', models.CharField(help_text='sponsor person', max_length=50)),
                ('sponsor_type', models.CharField(choices=[('financial', 'Financial'), ('spiritual', 'Spiritual'), ('other', 'Other')], default='other', help_text='type of support', max_length=30)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
                ('about', models.TextField(help_text='about sponsor', max_length=1000)),
                ('logo', models.ImageField(default='default.jpg', help_text="company's logo", upload_to='pics/sponsors/')),
                ('account_status', models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive')], default='deactive', max_length=20)),
                ('event_name', models.ForeignKey(help_text='Choose Your Event:', on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
        ),
    ]
