# Generated by Django 2.2.3 on 2019-07-20 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_sponsor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsor',
            old_name='event_name',
            new_name='event',
        ),
    ]
