dist: xenial # required for python 3.7
language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
services:
  - postgresql
before_script:
  - psql -c "CREATE USER tedx WITH PASSWORD '1234';" -U postgres
  - psql -c "CREATE DATABASE tedx;" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE tedx TO tedx;" -U postgres
  - psql -c "ALTER USER tedx CREATEDB;" -U postgres
script:
  - python manage.py test
