# Generated by Django 2.2.3 on 2019-07-24 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speaker',
            old_name='event_name',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='sponsor',
            old_name='event_name',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='event_name',
            new_name='event',
        ),
    ]
